### ISSUE TITLE
2.0.0扫描功能失效

### ISSUE THREAD

**Issue by xinruhu** [perlh/Wavely#34]
![image](https://github.com/user-attachments/assets/8bd1ef55-2fef-4acd-832e-af67fe4236f4)
![image](https://github.com/user-attachments/assets/bfefba22-4ae6-4d29-b9ef-bedd9a1934d5)
通过靶场发现对应扫描功能失效

**Comment by perlh** [comment]
![image](https://github.com/user-attachments/assets/0aa581cc-dd3e-43bb-9053-c48144379cd3)
是一个bug，当加上/后，扫描不出来，把/去掉就可以扫描出来，下个版本修复。

**Comment by perlh** [comment]
版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1）

**Comment by perlh** [comment]
> 版本已修复，请更新版本至2.0.1（[https://github.com/perlh/Wavely/releases/tag/v2.0.1）](https://github.com/perlh/Wavely/releases/tag/v2.0.1%EF%BC%89)

**Comment by xinruhu** [comment]
好，师傅辛苦了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月28日(周六) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)




 
版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1）

**Comment by xinruhu** [comment]
都是Mac版本，还没有win版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月28日(周六) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)




  
版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1）

**Comment by perlh** [comment]
稍等，正在编译中





------------------ 原始邮件 ------------------
发件人: xinruhu ***@***.***&gt;
发送时间: 2024年12月28日 22:12
收件人: perlh/Wavely ***@***.***&gt;
抄送: Perlh ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)

**Comment by perlh** [comment]
已更新Wavely 2.0.1 windows安装程序包，https://github.com/perlh/Wavely/releases/tag/v2.0.1




贺述明
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "perlh/Wavely"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月28日(星期六) 晚上10:12
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)





 都是Mac版本，还没有win版本 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年12月28日(周六) 晚上10:05 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 
 
 
 
 
    
 版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1）

**Comment by xinruhu** [comment]
师傅，同一个模板和url，还是有俩个url没检测到。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月28日(周六) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)




 已更新Wavely 2.0.1 windows安装程序包，https://github.com/perlh/Wavely/releases/tag/v2.0.1 
 
 
 
 
 贺述明 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "perlh/Wavely"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年12月28日(星期六) 晚上10:12 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 
 
 
 
 
 
  都是Mac版本，还没有win版本  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2024年12月28日(周六) 晚上10:05  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)  
   
   
   
   
      
  版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1）

**Comment by perlh** [comment]
> 师傅，同一个模板和url，还是有俩个url没检测到。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月28日(周六) 晚上10:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 已更新Wavely 2.0.1 windows安装程序包，https://github.com/perlh/Wavely/releases/tag/v2.0.1  ***@***.*** &amp;nbsp;
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "perlh/Wavely" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2024年12月28日(星期六) 晚上10:12 ***@***.***&amp;gt;; ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 主题:&amp;nbsp;Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 都是Mac版本，还没有win版本
> ---原始邮件--- 发件人: ***@***.***&amp;amp;gt; 发送时间: 2024年12月28日(周六) 晚上10:05 收件人: ***@***.***&amp;amp;gt;; 抄送: ***@***.******@***.***&amp;amp;gt;; 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
请问你说的是创建多个扫描任务，同一个模板和url导致没检测出来吗？

**Comment by xinruhu** [comment]
对，分开创建单个或者多个都有一些没扫描出来，师傅可参考我附的图片



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月29日(周日) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)




  
师傅，同一个模板和url，还是有俩个url没检测到。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月28日(周六) 晚上10:27 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 已更新Wavely 2.0.1 windows安装程序包，https://github.com/perlh/Wavely/releases/tag/v2.0.1  @.*** &amp;nbsp;
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "perlh/Wavely" @.&amp;gt;; 发送时间:&amp;nbsp;2024年12月28日(星期六) 晚上10:12 @.&amp;gt;; @.&amp;gt;;"State @.&amp;gt;; 主题:&amp;nbsp;Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 都是Mac版本，还没有win版本
 ---原始邮件--- 发件人: @.&amp;amp;gt; 发送时间: 2024年12月28日(周六) 晚上10:05 收件人: @.&amp;amp;gt;; 抄送: @.@.&amp;amp;gt;; 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
 请问你说的是创建多个扫描任务，同一个模板和url导致没检测出来吗？

**Comment by perlh** [comment]
1、在不同的扫描任务中，如果扫描目标和POC相同，确实可能会出现这样的问题，原因主要为nuclei扫描匹配会进行回调，回调时同时根据模版和目标判断这个扫描回调所属的扫描任务。2、建议在不同的扫描任务中，不要出现模版和目标都一样的情况，如果在不同扫描任务使用同一个模板和url，扫描结果可能只会存在某个扫描任务中，后续也会对算法进行修改，应该可以解决这个问题。
&nbsp;


贺述明
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月29日(星期天) 下午3:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34)














 对，分开创建单个或者多个都有一些没扫描出来，师傅可参考我附的图片 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年12月29日(周日) 下午3:06 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 
 
 
 
 
    
 师傅，同一个模板和url，还是有俩个url没检测到。 
  … 
  ---原始邮件--- 发件人: @.&amp;gt; 发送时间: 2024年12月28日(周六) 晚上10:27 收件人: @.&amp;gt;; 抄送: @.@.&amp;gt;; 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 已更新Wavely 2.0.1 windows安装程序包，https://github.com/perlh/Wavely/releases/tag/v2.0.1  @.*** &amp;amp;nbsp; 
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "perlh/Wavely" @.&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2024年12月28日(星期六) 晚上10:12 @.&amp;amp;gt;; @.&amp;amp;gt;;"State @.&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 都是Mac版本，还没有win版本 
  ---原始邮件--- 发件人: @.&amp;amp;amp;gt; 发送时间: 2024年12月28日(周六) 晚上10:05 收件人: @.&amp;amp;amp;gt;; 抄送: @.@.&amp;amp;amp;gt;; 主题: Re: [perlh/Wavely] 2.0.0扫描功能失效 (Issue #34) 版本已修复，请更新版本至2.0.1（https://github.com/perlh/Wavely/releases/tag/v2.0.1） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&amp;amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&amp;gt; 
  请问你说的是创建多个扫描任务，同一个模板和url导致没检测出来吗？
